-- ESTE QUERY GENERA UN VALOR UNICO DE 6 CARACTERES COMPUESTOS POR:
-- 3 CARACTERES INICIALES DE LA PARTE HEXADECIMAL DE UN VALOR MD5 ALEATORIO
-- SEGUIDO DE 3 CARACTERES QUE REPRESNTAN UN NUMERO ALEATORIO ENTRE 0 Y 999
-- CON 0 A LA IZQUIERDA PARA COMPLETAR LA LONGITUD DE 3 CARACTERES
SELECT CONCAT(SUBSTRING(MDS(RAND()),1,3),LPAD(FLOOR(RAND()*1000),3,'0'))
